# Generated by Django 4.2 on 2025-02-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notes',
            new_name='Note',
        ),
    ]
